---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      encoding: utf-8
      standard: "PSR1,PSR2"
      ignore_warnings: true
ratings:
  paths:
  - "src/**.php"
exclude_paths:
